### ISSUE TITLE
Why is the source code obfuscated?

### ISSUE THREAD

**Issue by aleclarson** [mikesmullin/mini-handlebars#1]
Thanks for making this! I wanted to look at the source code, but it's obfuscated. Could you please use a minifier and keep the source code readable?

**Comment by aleclarson** [comment]
I rewrote this library in TypeScript. https://www.npmjs.com/package/mini-hb

4kb minified

**Comment by mikesmullin** [comment]
some obfuscators have trouble with renaming ALL variables. i was manually obfuscating it. the `.coffee` version is the authoritative source with comments that explain many of the abbreviations. my version is ~1K minified, yours is ~4K. still, a TypeScript version is neat. 

rock on! 💯
